import { format, addDays } from "date-fns";

const today = new Date();
const d = (offset) => format(addDays(today, offset), "yyyy-MM-dd");

export const topics = [
  {
    name: "React",
    color: "#E7EFFF",
    entries: [
      { date: d(-17), hours: 17, state: "done" },
      { date: d(-15), hours: 24, state: "done" },
      { date: d(-12), hours: 22, state: "done" },
      { date: d(-10), hours: 13, state: "done" },
      { date: d(-7),  hours: 24, state: "upcoming" },
      { date: d(-4),  hours: 6,  state: "due"  },
      { date: d(-2),  hours: 13, state: "upcoming" },
      { date: d(0),   hours: 4,  state: "done" },
      { date: d(2),   hours: 20, state: "done" },
      { date: d(4),   hours: 4,  state: "upcoming" },
      { date: d(7),   hours: 9,  state: "upcoming" },
      { date: d(9),   hours: 24, state: "upcoming" },
      { date: d(13),  hours: 22, state: "upcoming" },
    ],
  },
  {
    name: "CSS",
    color: "#DFDFDF",
    entries: [
      { date: d(-12), hours: 16, state: "due"  },
      { date: d(-9),  hours: 24, state: "done" },
      { date: d(-6),  hours: 8,  state: "upcoming" },
      { date: d(-4),  hours: 24, state: "done" },
      { date: d(-2),  hours: 13, state: "due"  },
      { date: d(2),   hours: 6,  state: "upcoming" },
      { date: d(5),   hours: 8,  state: "done" },
      { date: d(8),   hours: 12, state: "upcoming" },
      { date: d(12),  hours: 17, state: "upcoming" },
    ],
  },
  {
    name: "Typescript",
    color: "#FFEE06",
    entries: [
      { date: d(-15), hours: 9,  state: "done" },
      { date: d(-12), hours: 6,  state: "done" },
      { date: d(-10), hours: 20, state: "due"  },
      { date: d(-7),  hours: 19, state: "upcoming" },
      { date: d(-4),  hours: 24, state: "done" },
      { date: d(-1),  hours: 6,  state: "done" },
      { date: d(0),   hours: 4,  state: "upcoming" },
      { date: d(1),   hours: 15, state: "upcoming" },
      { date: d(3),   hours: 11, state: "upcoming" },
      { date: d(6),   hours: 10, state: "upcoming" },
      { date: d(9),   hours: 5,  state: "upcoming" },
      { date: d(12),  hours: 24, state: "upcoming" },
    ],
  },
  {
    name: "Motion",
    color: "#FFEBC5",
    entries: [
      { date: d(-16), hours: 8,  state: "done" },
      { date: d(-15), hours: 19, state: "done" },
      { date: d(-13), hours: 13, state: "done" },
      { date: d(-9),  hours: 24, state: "done" },
      { date: d(-7),  hours: 12, state: "done" },
      { date: d(-5),  hours: 14, state: "done" },
      { date: d(-2),  hours: 8,  state: "done" },
      { date: d(0),   hours: 7,  state: "done" },
      { date: d(2),   hours: 22, state: "done" },
      { date: d(4),   hours: 19, state: "upcoming" },
      { date: d(7),   hours: 24, state: "upcoming" },
      { date: d(10),  hours: 24, state: "upcoming" },
      { date: d(13),  hours: 17, state: "upcoming" },
    ],
  },
  {
    name: "SVG",
    color: "#CDFFC8",
    entries: [
      { date: d(-13), hours: 24, state: "due"  },
      { date: d(-11), hours: 9,  state: "done" },
      { date: d(-8),  hours: 10, state: "upcoming" },
      { date: d(-6),  hours: 16, state: "done" },
      { date: d(-4),  hours: 24, state: "done" },
      { date: d(0),   hours: 7,  state: "done" },
      { date: d(1),   hours: 11, state: "done" },
      { date: d(5),   hours: 24, state: "upcoming" },
      { date: d(7),   hours: 13, state: "upcoming" },
      { date: d(10),  hours: 3,  state: "upcoming" },
      { date: d(13),  hours: 11, state: "upcoming" },
    ],
  },
  {
    name: "Three",
    color: "#F3F3F3",
    entries: [
      { date: d(-15), hours: 24, state: "done" },
      { date: d(-12), hours: 22, state: "done" },
      { date: d(-9),  hours: 15, state: "done" },
      { date: d(-6),  hours: 14, state: "upcoming" },
      { date: d(-4),  hours: 20, state: "upcoming" },
      { date: d(-1),  hours: 4,  state: "done" },
      { date: d(0),   hours: 8,  state: "done" },
      { date: d(3),   hours: 24, state: "done" },
      { date: d(6),   hours: 9,  state: "upcoming" },
      { date: d(9),   hours: 13, state: "upcoming" },
      { date: d(13),  hours: 23, state: "upcoming" },
    ],
  },
  {
    name: "NextJS",
    color: "#F5EAFF",
    entries: [
      { date: d(-13), hours: 17, state: "done" },
      { date: d(-10), hours: 24, state: "done" },
      { date: d(-7),  hours: 20, state: "done" },
      { date: d(-5),  hours: 21, state: "upcoming" },
      { date: d(-1),  hours: 9,  state: "done" },
      { date: d(3),   hours: 24, state: "upcoming" },
      { date: d(6),   hours: 20, state: "upcoming" },
      { date: d(8),   hours: 17, state: "upcoming" },
      { date: d(12),  hours: 24, state: "upcoming" },
    ],
  },
  {
    name: "D3",
    color: "#D3D2FF",
    entries: [
      { date: d(-16), hours: 21, state: "done" },
      { date: d(-13), hours: 15, state: "done" },
      { date: d(-10), hours: 12, state: "done" },
      { date: d(-8),  hours: 14, state: "upcoming" },
      { date: d(-5),  hours: 9,  state: "due"  },
      { date: d(-2),  hours: 17, state: "done" },
      { date: d(1),   hours: 13, state: "done" },
      { date: d(4),   hours: 10, state: "upcoming" },
      { date: d(6),   hours: 8,  state: "upcoming" },
      { date: d(9),   hours: 19, state: "upcoming" },
      { date: d(12),  hours: 14, state: "upcoming" },
    ],
  },
];
